feature-management:
  feature-flags:
    beta:
      enabled-for:
        -
          name: timeWindowFilter
          parameters:
            Start: "2024-05-06T09:00:00+08:00"
            End: "2024-05-06T17:00:00+08:00"
            Recurrence:
              Pattern:
                Type: "Weekly"
                Interval: 1
                DaysOfWeek:
                  - Monday
                  - Tuesday
              Range:
                Type: "NoEnd"